### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by hsb1995** [mbzuai-oryx/groundingLMM#7]
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/f89a418b-42a0-498e-b3ac-adb4fbefe62c)
Hello dear author, your work is quite great! I will reproduce your work code as soon as it is released today.

I have been keeping an eye on your work, and today when I reproduced your code, I encountered the demo section. It has encountered this situation, and the above is the error that occurred after I reproduced it.

There have also been many issues in the code.

Could you please help answer this question.
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/20572ac8-324c-4f6e-9836-6be95541d243)

**Comment by hsb1995** [comment]
I have followed your instructions step by step and still found the above problem. Could you please explain, Professor? Thank you

**Comment by hsb1995** [comment]
@hanoonaR

**Comment by hanoonaR** [comment]
Hi @hsb1995 ,

Thank you for your interest in our work. It seems the issue is related to the Gradio installation for our demo. We've updated the system requirements [system requirements](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/offline_demo.md#system-requirements) in our demo documentation. Please make sure you are using the correct versions of Gradio and Gradio-Client:
- Gradio version 3.35.2
- Gradio-Client version 0.2.7

In addition, we've provided a conda environment setup in a [.zip](https://drive.google.com/file/d/1BN10oChcoKDDd0zC8tU88JcrfmLpKpkB/view?usp=sharing) file. You can follow the installation steps outlined in [install.md](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/install.md) to configure the environment properly.

If the problem persists after these steps, please let us know. We're here to assist. Thank you.

**Comment by hsb1995** [comment]
Dear author, hello. I have made the necessary changes according to your request, but the current issue is that I keep spinning and cannot generate a reply. And it cannot be framed in the local webpage image. Could you please again.
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/237ba728-c8d7-4adc-ad59-5bb56b618354)


This error is reported in the code：There is no problem with the environment this time
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/97554fab-6f26-4283-b86f-0dd828f451c7)
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/ddc0234d-31b9-4e32-978d-a202fd494f10)

**Comment by sahalshajim** [comment]
Hi @hsb1995 
 
 Please install `pydantic==1.10.12` and `pydantic-core==2.0.1`. 

```bash
pip install pydantic==1.10.12
pip install pydantic-core==2.0.1
```

This is updated in the [requirements.txt](https://github.com/mbzuai-oryx/groundingLMM/blob/main/requirements.txt) file as well. 
Thank you for pointing it out.

**Comment by Songlinlsl** [comment]
Same problem as you met in the beginning. The gradio and pydantic version are same as the requirements mentioned.  do you solve the problem? @hsb1995

**Comment by hsb1995** [comment]
> Same problem as you met in the beginning. The gradio and pydantic version are same as the requirements mentioned. do you solve the problem? @hsb1995


Follow the above steps to solve the problem

**Comment by remvanthull** [comment]
I followed the steps above, but the problem still persists for me...

**Comment by mmaaz60** [comment]
Hi @remvanthull,

Thank you for your interest in our work. Can you please double check the version of pydantic and gradio as below?

```
pydantic==1.10.12
pydantic-core==2.0.1
gradio==3.35.2
gradio-client==0.2.7
```

In case if your versions matches with the above, please share the exact steps you followed to setup the environment so that we can help further. Thank you.

**Comment by tuning12** [comment]
Hi, I have tried to fix this problem.
I tried to replace the defination of class 'ImageSketcher' in utils/markdown_utils, and it started to show the output picture.
`class ImageSketcher(gr.Image):
    """Code is from https://github.com/ttengwang/Caption-Anything/blob/main/app.py#L32.

    Fix the bug of gradio.Image that cannot upload with tool == 'sketch'.
    """

    is_template = True  # Magic to make this work with gradio.Block, don't remove unless you know what you're doing.

    def __init__(self, **kwargs):
        super().__init__(tool='boxes', **kwargs)

    def preprocess(self, x):
        if x is None:
            return x
        self.DEFAULT_TEMP_DIR = 'gradio_out/' #Make Dir if required
        if self.tool == 'boxes' and self.source in ['upload', 'webcam']:
            if isinstance(x, str):
                x = super().preprocess(x)
                x = {'image': x, 'boxes': []}
            else:
                assert isinstance(x, dict)
                assert isinstance(x['image'], str)
                assert isinstance(x['boxes'], list)
        return x`

**Comment by remvanthull** [comment]
This solved it for me, thanks!!

**Comment by Lay-du** [comment]
> This solved it for me, thanks!!

Hello, I meet the same question that I can't draw the bounding boxes. Can you tell me your solution?

**Comment by Lay-du** [comment]
> This solved it for me, thanks!!
@remvanthull 
Hello, I meet the same question that I can't draw the bounding boxes. Can you tell me your solution?

**Comment by remvanthull** [comment]
Hi @Lay-du , I never got the bounding boxes to work unfortunately, only the error was solved.

**Comment by sajeedmehrab** [comment]
This issue is still present, with the correct versions of modules installed. 

The comment in https://github.com/mbzuai-oryx/groundingLMM/issues/7#issuecomment-1890992129 gets rid of of the assertion error.

However, drawing the bboxes do not still work.
